### ISSUE TITLE
Bug na criação de conta

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#15]
Tentei criar uma conta do tipo empreendedor, selecionando uma imagem para o perfil. Botão concluir não funcionou. Não consigo saber o motivo. Tentei sem imagem e o botão concluir no passo 4 também não funcionou.

**Comment by andredeloliveira** [comment]
Eu estou fazendo o da empresa. Não está nada porque o objeto estava vazio.
Tadashi já começou? Eu tenho +- tudo pronto (nos controllers) só falta alterar a view para ficar melhor

**Comment by tadasshi** [comment]
Pode deixar a view comigo André.  ^^
