### ISSUE TITLE
Adicionar o Indicador de Etapa no Cadastro

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#17]
Adicionar componente (JavaScript, Angular ou Bootstrap) para identificar a etapa em que se encontra no registro.

![03 pessoal descricao](https://cloud.githubusercontent.com/assets/15639850/11024925/70023b9a-867c-11e5-8daf-ba82ea833643.png)

![04 pessoal expertise](https://cloud.githubusercontent.com/assets/15639850/11024928/7b59ae06-867c-11e5-893b-a295ec8228e8.png)

**Comment by tadasshi** [comment]
- Inseri barra de prograssão;

**Comment by fabianoneumann** [comment]
Minha resolução é 1920x1080. Com a tela maximizada o componente não fica centralizado (está um tanto à esquerda) e a medida que eu mudo a largura da tela ele zoa. 

![mentorias tela registro](https://cloud.githubusercontent.com/assets/15639850/11104256/b1bce682-88ae-11e5-8cec-fc0a099ea13e.png)

**Comment by fabianoneumann** [comment]
Show de bola! Acho que dá para diminuir a largura da linha que separa os pickers no indicador de etapa para 1/3 do tamanho que está, acredito que vai resolver o lance de pular linha quando a tela fica pequena demais.

**Comment by tadasshi** [comment]
Checa novamente por favor.

**Comment by fabianoneumann** [comment]
Ajustar tamanho de cada linha entre as caixas do indicador de progresso para metade do tamanho atual, daí pode fechar a issue Tadashi.

![mentorias indicador de progresso](https://cloud.githubusercontent.com/assets/15639850/11138058/b9d30b52-89a4-11e5-8c67-b0b5c219f5bb.png)

**Comment by fabianoneumann** [comment]
Pode ficar perto uma da outra, não tem problema, usa a primeira imagem da issue como referência qualquer coisa.

**Comment by tadasshi** [comment]
Diminui.

**Comment by tadasshi** [comment]
Esse aqui falta validar.

**Comment by fabianoneumann** [comment]
Não consigo ver a alteração aqui, foi dado deploy depois dessa correção?

**Comment by fabianoneumann** [comment]
segue o imagem que como fica aqui:

![mentorias](https://cloud.githubusercontent.com/assets/15639850/11165682/50214796-8afd-11e5-89fb-2a5ed9b0bae6.png)
