### ISSUE TITLE
Aumentar o espaçamento entre as linhas e acertar os pickers no registro do usuário passo 1

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#18]
Nossa tela é possível dar uma melhorada no espaço entre os campo nome, e-mail e senha, bem como melhorar o seletor, que quando nenhum selecionado fica com um -.

![02 pessoal nome novo](https://cloud.githubusercontent.com/assets/15639850/11024985/0808de26-867d-11e5-8678-ef6c11b3ae2f.png)

**Comment by tadasshi** [comment]
- Inseri o espaçamento,
- Campo input[type=radio] personalizado;
- Ajustei os botões;
- Inseri barra de prograssão;

**Comment by fabianoneumann** [comment]
Maravilha, melhorou bastante. Precisa fazer alguns ajustes para modificação do tamanho da tela.

A medida que altero a largura da janela, o texto da opção à esquerda gruda no picker da opção à direita, assim como os botões voltar e próximo quando ficam um em cima do outro.

Dependendo do tamanho, o picker e o texto da mesma opção ficam em linhas diferentes, ideal é que os dois passem para a linha de baixo quando não couber, separando um do outro em último caso.

Tadashi, se tiver com issues mais relevantes deixe essa para depois.

**Comment by tadasshi** [comment]
Corrigido.
