### ISSUE TITLE
Backgroup com bug

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#19]
Background não está acompanhando largura para telas com resolução 1920x1080.
Os componentes estão ficando fora da imagem.

**Comment by fabianoneumann** [comment]
Aqui voltou a dar problema com a imagem de background. Ela fica com largura menor do que o tamanho dos componentes e com o scroll para baixo ela fica menor em altura.

**Comment by tadasshi** [comment]
Corrigido.
