### ISSUE TITLE
Linhas na descrição profissional na tela de registro

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#22]
Adicionar as linhas no campo de descrição.

![03 pessoal descricao](https://cloud.githubusercontent.com/assets/15639850/11025214/a068a0a0-867f-11e5-8e2e-227711140a06.png)

**Comment by tadasshi** [comment]
Fabiano. Essas linhas do campo de descrição, é um fundo. Preciso de um frame deste fundo, para que através deste eu possa gerar o padrão que faz essas linhas. A altura deste frame é arbritaria.

**Comment by jeffmaran** [comment]
TadaSshi da uma olhada nisso antes
http://jsfiddle.net/minitech/WkM7M/

**Comment by tadasshi** [comment]
Vou testar aqui, se der certo será esse mesmo.

**Comment by tadasshi** [comment]
Jeff, essa sugestão também funcionou como um charme. Eu o adaptei para oque precisamos e ficou ótimo. Vlw. Cara esse codepen é show de bola. Já até me cadastrei nele. Codepen for life. :D

**Comment by jeffmaran** [comment]
:dancers:

**Comment by tadasshi** [comment]
- Linhas de descrição inseridas.
