### ISSUE TITLE
Melhorar posicionamento dos componentes na tela de login

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#23]
Dar uma melhorada no espaçamento entre os componentes e corrigir os labels de registro e equecimento de senha.

![01 landing page](https://cloud.githubusercontent.com/assets/15639850/11025235/d501c83c-867f-11e5-9602-f658e99d3b0a.png)

**Comment by tadasshi** [comment]
Fabiano. Valida esta issue para min fazendo favor.

**Comment by tadasshi** [comment]
Done
