### ISSUE TITLE
Adicionar a tela com campo de e-mail para reset de senha.

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#26]
Tela a ser chamada quando o usuário clicar no link "Esqueceu sua senha?"

**Comment by tadasshi** [comment]
Tela pronta. /recuperar-senha

**Comment by fabianoneumann** [comment]
Não consegui testar, este endereço me redireciona para a tela de login (como quando eu digito qlqr rota que não existe). Existe uma ação para o label "Esqueceu sua senha", a qual redireciona para a rota /resetSenha. Se quiser pode usar essa rota.

**Comment by tadasshi** [comment]
hheehe, to fazendo deploy.

**Comment by tadasshi** [comment]
Encontrei outro errinho bobo e estou corrigindo antes. Não achei que fosse ver agora.

**Comment by fabianoneumann** [comment]
Maravilha.
