### ISSUE TITLE
Upload de imagem e lib utilizada

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#29]
Resolver o upload de imagens.

Gostaria que verificassem qual das libs estão usando (skeleton ou bootstrap), visto que ambas criam o grid da página e só precisamos de uma, assim tiramos o que for desnecessário.

**Comment by jeffmaran** [comment]
Pessoal neste commit fiz alguns ajustes, podemos testar crossbrowser ok? ver se precisa de reparo em algum navegador. Segue link

https://github.com/andredeloliveira/mentorias/commit/2b9c40d0521f5652e84f1f074b0e8aacf37c2719

**Comment by andredeloliveira** [comment]
Beleza. Aqui tá funcionando. A única parada é que fica 100% do tamanho col-md-12. Você consegue arrumar pra ficar pequeno novamente? Porque quando é redimencionado ele fica doidão

**Comment by andredeloliveira** [comment]
Comentei na thread errada. Estamos só utilizando o bootstrap agora.
