### ISSUE TITLE
Permitir login e registro via Aplicativos Mobile

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#3]

**Comment by andredeloliveira** [comment]
API feita. Por favor, peça para o desenvolvedor mobile para testar e dizer se ele precisa de alguma função específica. Os métodos manipulam o banco diretamente.

**Comment by andredeloliveira** [comment]
Tudo certo com essa Issue?

**Comment by fabianoneumann** [comment]
A princípio sim, se precisar alterar algo te aviso, mas essa issue já podemos fechar.
Combinei com o developer das apps de fazer o levantamento dos outros serviços no sábado agora, daí qualquer novidade criamos novas issues.

**Comment by andredeloliveira** [comment]
Beleza! Isso é bom! Estou fechando agora, qualquer coisa é só criar outra
