### ISSUE TITLE
Bug no componente de upload de arquivos

### ISSUE THREAD

**Issue by jeffmaran** [andredeloliveira/mentorias#32]
Exception while parsing DDP Error: Custom EJSON type FS.File is not defined(…)

Pessoal o bug é resolvido retirando o componente autopublish do meteor, qual o impacto de retirarmos essa lib, pelo que vi precisaremos publicar no banco na mão.

**Comment by tadasshi** [comment]
Se for só isso, o impacto é quase nenhum. Pelo que me lembro vocês terão de usar o 'publish' no server-side e o 'subscribe' no client-side. Isso vai permitir que você acesse os objetos com os dados no server através do client sem o módulo 'autopublish'.

**Comment by andredeloliveira** [comment]
O autopublish já foi removido. Isso é causado pelo CollectionFileFS. Eu já li a issue lá no github dos caras. Instalando o EJSON(que já foi instalado) era pra resolver. Isso é um bug deles, mas na verdade não é um bug. Segundo a thread, o EJSON não está carregando antes de tudo, por isso gera essa Exception. Eles fecharam a issue como se fosse resolvida, re-abriram mas continua a mesma coisa. Aina não se se sabe a causa, mas diz a lenda que não tem efeitos negativos. Até agora não teve.

**Comment by tadasshi** [comment]
Nice.

**Comment by jeffmaran** [comment]
entendi, massa. Vamos que vamos se aparecer denovo aqui eu aviso
