### ISSUE TITLE
Duvida Cruel que me tomou + de 7hs :(

### ISSUE THREAD

**Issue by andredeloliveira** [andredeloliveira/mentorias#33]
Então piazada. Seguinte. Procurei por tudo e não sei mais o que fazer, não tenho respostas. Talvez voces tenham.

Eu to afim de pegar os usuarios do banco. Até ai tudo bem.

no arquivo /server/users.js eu uso o publish:

` Meteor.publish('users', function(){
  return Meteor.users.find({}, {fields: {emails:1, profile: 1}});

});
`

e no controller eu uso:

`$scope.users = $meteor.collection(Meteor.users,false).subscribe('users');`

Os usuários retornam porém, só consigo usar com ng-repeat, não consigo colocar eles em outro array. Algum meio de resolver? 

Valeu

**Comment by tadasshi** [comment]
Tentou imprimir o objeto no console? Para ver como os objetos estão organizados. Se eu não me engano a função 'fetch()' retorna o objeto dos dados.

**Comment by andredeloliveira** [comment]
Sim. Tentei. É um objeto com os docs como se fossem properties. Mas é dificil acessar. Não existe a função fetch para o objeto do tipo AngularMeteorCollection (que é o que retorna)

**Comment by tadasshi** [comment]
Faz push. Posso tentar ajudar.

**Comment by jeffmaran** [comment]
gurizada fica susse usa o underscore carrega ja no meteor pra isso
vamos fazer um pair programming ai posso ajudar melhor
 ou me diz onde precisa do array que eu comito agora

**Comment by andredeloliveira** [comment]
vou fazer o commit e ai voce faz a sua mágica! Valeu irmão

**Comment by jeffmaran** [comment]
massa comenta o ponto onde precisa com  #purungus pra eu achar :) eh nois

**Comment by andredeloliveira** [comment]
Resolvido piazada. Não sei o que eu tinha feito errado antes, mas foi feito. Valeu o esforço moçada!

**Comment by jeffmaran** [comment]
Massa
