### ISSUE TITLE
Ajustar posicionamento dos botões das redes sociais e 3 botões à direita 

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#34]
Na tela do perfil, a medida que a tela fica mais larga a coluna das redes sociais aumenta, de modo que o terceiro ícone vai para a direita e fica do lado do primeiro.

Quando a tela vai ficando menor, os botões à direita (Mensagens, Agenda e ações) estouram do componente.

Rever o posicionamento dos componentes da barra principal (onde tem os botões citados, bem como foto do perfil, descrição, avaliações, etc) quando a tela é redimensionada. São vários os tamanhos onde zoa os componentes.

**Comment by tadasshi** [comment]
Pronta
