### ISSUE TITLE
Adicionar placeholeder e comportamento do seletor Produtos no cadastro de Empresa

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#44]
Neste campo devem aparecer as categorias de produtos pré-cadastradas. Usar o que temos de tags como referência. Placeholder: Produtos.

Algumas categorias: Jogos Digitais, Softwares, Eletrônicos, Realidade Virtual, Eficiência Energética, Bioarquitetura.

**Comment by tadasshi** [comment]
Adicionei o seletor, falta acertar o comportamento. A questão vizual acertarei juntamente com a issue #43.

**Comment by andredeloliveira** [comment]
O seletor vai ser no mesmo estilo que nos outros?

**Comment by fabianoneumann** [comment]
Isso.

**Comment by fabianoneumann** [comment]
![08 empresa nome](https://cloud.githubusercontent.com/assets/15639850/11171647/34b8d610-8bdc-11e5-9d17-f18c2e1a158e.png)
