### ISSUE TITLE
Pintura do quadrado de indicador de progresso no registro e distância entre seletores

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#46]
Nas referências deles, o tamanho do quadrado do indicador de etapa de registro é o mesmo do seletor de tipo de conta e sexo, além de distância menor entre as opção de seleção.

Diminuir o tamanho dos quadrados dos seletores e aumentar o quadrado de progresso deixando a pintura vazada, assim como nos seletores.

Ajustar posição das opções.

![02 pessoal nome novo](https://cloud.githubusercontent.com/assets/15639850/11164201/b37eda9c-8ad0-11e5-9212-16d21c89b56a.png)

**Comment by tadasshi** [comment]
Fixed

**Comment by fabianoneumann** [comment]
Acho que dá para diminuir um pouco mais os quadrados.

Em algumas larguras de tela, o quadrado e o texto das opções estão sendo separados de linha.
Poderiam ter um padding esquerdo (opções da esquerda) e direito (opções da direita) maior, dando impressão de centralizar um pouco mais e aproximar as opções em cada linha.

**Comment by fabianoneumann** [comment]
Print da separação entre caixa de seleção e texto correspondente.

![image](https://cloud.githubusercontent.com/assets/15639850/11169675/4abd30c8-8ba5-11e5-9170-2e610df0afd0.png)
