### ISSUE TITLE
Listagem das Tags

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#5]
Nos registros dos perfís, as tags devem ser listadas (pré-cadastradas) e o campo de digitação apresenta as tags filtrando de acordo com o que está sendo digitado.

**Comment by andredeloliveira** [comment]
E como será feito o pré-cadastro? Hard-coded para essa primeira etapa? Se sim, será bem rápido, senão teremos que fazer uma interface de cadastro das tags.]

**Comment by fabianoneumann** [comment]
Hard-coded mesmo. A lista vai ser grande más não tem problema.

**Comment by andredeloliveira** [comment]
Me passa a lista aí que já podemos fechar mais uma issue.

**Comment by fabianoneumann** [comment]
Puts, não sei ainda, só colocar uma lista qualquer e deixar comentado no código que eu mesmo mudo depois, no problem, pode fechar a issue ao concluir.

Nas telas que recebemos (olhando de apps e web) temos as seguintes expertises: Consultoria, Auditoria, Web Design, Programação, Design de Interface, Design de Produto, Design Editorial, Design Gráfico, Tecnologia, Marketing, Economia, Arquitetura, Alimentação, Engenharia, Saúde, Turismo e Mobilidade.
