### ISSUE TITLE
Avaliação da Sessão de Mentoria pelo Mentor

### ISSUE THREAD

**Issue by fabianoneumann** [andredeloliveira/mentorias#7]
Tela de avaliação da empresa pelo Mentor, para que seja possível gerar a média de avaliações da empresa. Necessário guardar histórico de avaliações para cada empresa.

Em uma issue futura faremos o botão correspondente chamar esta tela.

Segue imagem:
![24 avaliacao mentoria](https://cloud.githubusercontent.com/assets/15639850/10954398/34d3e0e6-8334-11e5-94be-bea2b815c64c.png)

**Comment by tadasshi** [comment]
Como não há botão e nem contexto aonde inseri-las, eu as coloquei na página /modais. Detalhe, usei um gerador de imagens randomicas para preencher o perfil da empresa. As modais enviadas por eles estão seguindo padrões diferentes, fiz um esforço e as deixei no mesmo padrão. Eles também não enviaram as estrelas, então usei uma do bootstrap.
